version: "1.0"

steps:
  - name: build image dry run
    image: target/vela-kaniko:v0.8.0
    parameters:
      dry_run: true
      repo: asphyxia-docker
      tags:
        - dry_run
    ruleset:
        event: [push, pull_request]
        branch: [main]

  - name: build image
    image: target/vela-kaniko:v0.8.0
    secrets:
      - source: docker_username
        target: parameter_username
      - source: docker_password
        target: parameter_password
    parameters:
      dry_run: true
      # TODO Vela update Kaniko to support pushing to insecure registries
      #   https://github.com/go-vela/community/issues/470
      # insecure: true
      # insecure_registries:
      #   - docker.internal.mapes.info
      registry: docker.internal.mapes.info
      repo: docker.internal.mapes.info/asphyxia-docker
      tags:
        - "${VELA_BUILD_TAG:##v}"
    ruleset:
      event: tag
  
secrets:
  - name: docker_username
    type: org
    key: tmapes/docker_username
  - name: docker_password
    type: org
    key: tmapes/docker_password