version: "1.0"

steps:
  - name: build image dry run
    image: target/vela-kaniko:v0.8.0
    parameters:
      dry_run: true
      registry: docker.internal.mapes.info
      repo: asphyxia-core
      tags:
        - dry_run
    ruleset:
        event: [push, pull_request]
        branch: [main]

  - name: build image
    image: target/vela-kaniko:v0.8.0
    secrets:
      - source: docker_username
        target: parameter_username
      - source: docker_password
        target: parameter_password
    parameters:
      registry: docker.internal.mapes.info
      repo: asphyxia-core
      tags:
        - "${VELA_BUILD_TAG:##v}"
    ruleset:
      event: tag
  
secrets:
  - name: docker_username
    type: org
    key: tmapes/docker_username
  - name: docker_password
    type: org
    key: tmapes/docker_password