version: "1.0"

steps:
  - name: build image dry run
    image: target/vela-kaniko:v0.13.0
    parameters:
      dry_run: true
      repo: tjmapes/asphyxia-docker
      tags:
        - dry_run
    ruleset:
        event: [push, pull_request]
        branch: [main]

  - name: build image
    image: target/vela-kaniko:v0.13.0
    secrets: [docker_username, docker_password]
    parameters:
      registry: https://index.docker.io/v1/
      repo: tjmapes/asphyxia-docker
      tags:
        - "${VELA_BUILD_TAG:##v}"
    ruleset:
      event: tag
  
secrets:
  - name: docker_username
    type: org
    key: tmapes/docker_username
    engine: native
  - name: docker_password
    type: org
    key: tmapes/docker_password
    engine: native
