services:
  server:
    image: docker.mapes.info/tjmapes/asphyxia-docker:v1.50.0c-2
    platform: linux/x86_64
    ports:
      - "8083:8083"
    environment:
      - HOST=0.0.0.0
      - PING_IP_ADDRESS=8.8.8.8
